version: '3'
services:

  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    ports:
      - "8081:80"
    env_file: ./api/db.env
    command: bash -c "npm i && npm run startdev"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3313:3306"
    env_file: ./api/db.env

  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/app
    depends_on:
      - db
      - api
    ports:
      - "8080:80"
    command: bash -c "npm i && npm run startdev"
